config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  resources :anthonies
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :articles
  get 'test/index'

  resources :users

end

app/models/anthony.rb
class Anthony < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    
    extend FriendlyId
    friendly_id :name, use: :slugged
end

app/controllers/anthonies_controller.rb
class AnthoniesController < ApplicationController
  before_action :set_anthony, only: [:show, :edit, :update, :destroy]

  # GET /anthonies
  # GET /anthonies.json
  def index
    @anthonies = Anthony.all
  end

  # GET /anthonies/1
  # GET /anthonies/1.json
  def show
  end

  # GET /anthonies/new
  def new
    @anthony = Anthony.new
  end

  # GET /anthonies/1/edit
  def edit
  end

  # POST /anthonies
  # POST /anthonies.json
  def create
    @anthony = Anthony.new(anthony_params)

    respond_to do |format|
      if @anthony.save
        format.html { redirect_to @anthony, notice: 'Anthony was successfully created.' }
        format.json { render :show, status: :created, location: @anthony }
      else
        format.html { render :new }
        format.json { render json: @anthony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anthonies/1
  # PATCH/PUT /anthonies/1.json
  def update
    respond_to do |format|
      if @anthony.update(anthony_params)
        format.html { redirect_to @anthony, notice: 'Anthony was successfully updated.' }
        format.json { render :show, status: :ok, location: @anthony }
      else
        format.html { render :edit }
        format.json { render json: @anthony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anthonies/1
  # DELETE /anthonies/1.json
  def destroy
    @anthony.destroy
    respond_to do |format|
      format.html { redirect_to anthonies_url, notice: 'Anthony was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anthony
      @anthony = Anthony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anthony_params
      params.require(:anthony).permit(:title, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:range_start, :range_end)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :slug)
    end
end

app/helpers/anthonies_helper.rb
module AnthoniesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/anthonies/_form.html.erb
<%= form_for(@anthony) do |f| %>
  <% if @anthony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anthony.errors.count, "error") %> prohibited this anthony from being saved:</h2>

      <ul>
      <% @anthony.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anthonies/edit.html.erb
<h1>Editing Anthony</h1>

<%= render 'form' %>

<%= link_to 'Show', @anthony %> |
<%= link_to 'Back', anthonies_path %>

app/views/anthonies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Anthonies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anthonies.each do |anthony| %>
      <tr>
        <td><%= anthony.title %></td>
        <td><%= anthony.description %></td>
        <td><%= link_to 'Show', anthony %></td>
        <td><%= link_to 'Edit', edit_anthony_path(anthony) %></td>
        <td><%= link_to 'Destroy', anthony, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anthony', new_anthony_path %>

app/views/anthonies/new.html.erb
<h1>New Anthony</h1>

<%= render 'form' %>

<%= link_to 'Back', anthonies_path %>

app/views/anthonies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @anthony.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @anthony.description %>
</p>

<%= link_to 'Edit', edit_anthony_path(@anthony) %> |
<%= link_to 'Back', anthonies_path %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :range_start %><br>
    <%= f.number_field :range_start %>
  </div>
  <div class="field">
    <%= f.label :range_end %><br>
    <%= f.number_field :range_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Galleries</h1>

    <% @galleries.each do |gallery| %>
    <div class="well" style="background-color: #303030;
    padding: 15px;
    margin: 70px auto;
    color: #11d5e6;">
      <% output = [] %>
  <% for i in gallery.range_start..gallery.range_end %>
  <% output << i  %>
  <% end %>
  
  <% string = "" %>
  <% output.each do |i| %>
  <%   string = string + i.to_s + "," %>
 <%  end %>
<% i = string.length - 1  %>
  
  <% if string[i] == "," %>
  <%   string[i] = " " %>
 <%  end %>
 <%=  final = "[gallery ids='#{string}' type='slider' height='600']" %>
  <p> <br/></p>
 <%=  p  "Your range is: #{string}" %>
 <p> <br/></p>
 <%=  p "Shortcode is " + final %>
    
        <p style="color: #1dce35;"><%= link_to 'Show', gallery %></p>
        <p style="color: #1dce35;"><%= link_to 'Edit', edit_gallery_path(gallery) %></p>
        <p style="color: #1dce35;"><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
    <% end %>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Range start:</strong>
  <%= @gallery.range_start %>
</p>

<p>
  <strong>Range end:</strong>
  <%= @gallery.range_end %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.slug %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @user.slug %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>